# 1 - Creating array 


In [1]:
import numpy as np 

In [2]:
# 1D array 

arr_1 = np.array([1,2,3,4,5,6,7,8])
arr_1


array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
# shape

arr_1.shape

(8,)

In [5]:
# dimension 
arr_1.ndim

1

# 2D array

In [6]:
#  creating 2 Dimenional array

In [8]:
arr_2 = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])
arr_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# dimension of array

arr_2.ndim

2

In [10]:
arr_2.shape

(3, 4)


# 3D array

In [12]:
arr_3 = np.array([
    [[1,2,3],[1,2,3],[1,2,3]],
    [[1,2,3],[1,2,3],[1,2,3]],
    [[1,2,3],[1,2,3],[1,2,3]]
])
arr_3

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [13]:
arr_3.shape

(3, 3, 3)

# create array using methods 


In [14]:
#1 -  arange(p1,p2,p3)
# create range of array 

a = np.arange(1 , 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
a = np.arange(1 , 21,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [16]:
# 2 - zeros mehod 


b = np.zeros((3,4))
b


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
type(b[0][0])

numpy.float64

In [22]:
b = np.zeros((3,4),dtype = np.int64)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [25]:
type(b[0][0])

numpy.int64

In [26]:
# 3 - ones method 

c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
type(c[0][0])

numpy.float64

In [30]:
c = np.ones((3,3),dtype = np.int16)

In [31]:
c

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [35]:
c = np.zeros((8,))
c

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
c = np.zeros((3,3,3))
c

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# 3 - Getting info of arrays

In [39]:
arr_1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
arr_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
arr_3

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [41]:
# Dimesion of array 

print(f"arr_1 array dimension : {arr_1.ndim}")
print(f"arr_2 array dimension : {arr_2.ndim}")
print(f"arr_3 array dimension : {arr_3.ndim}")

arr_1 array dimension : 1
arr_2 array dimension : 2
arr_3 array dimension : 3


In [42]:
# shape of array 


print(f"arr_1 array shape : {arr_1.shape}")
print(f"arr_2 array shape : {arr_2.shape}")
print(f"arr_3 array shape : {arr_3.shape}")

arr_1 array shape : (8,)
arr_2 array shape : (3, 4)
arr_3 array shape : (3, 3, 3)


In [46]:
# size of each element in array 


print(arr_1.itemsize)  # int data 
print(arr_2.itemsize)  # int data 
print(arr_3.itemsize)  # int data 

4
4
4


In [47]:
# check size of element in array 

print(arr_1.size)  
print(arr_2.size)   
print(arr_3.size)  

8
12
27


In [48]:
# find minimum value

print(arr_1.min())
print(arr_2.min())
print(arr_3.min())

1
1
1


In [49]:
# find Maximum value

print(arr_1.max())
print(arr_2.max())
print(arr_3.max())

8
12
3


In [50]:
# sum function 


print(arr_1.sum())


36


In [51]:
print(arr_2.sum())

78


In [53]:
# sum of rows and sum of columns 
# in numpy axis = 0 for columns 
# in numpy axis = 1 for rows 

print(arr_2.sum(axis = 0))
print(arr_2.sum(axis = 1))

[15 18 21 24]
[10 26 42]


In [54]:
# find mean value

print(arr_1.mean())
print(arr_2.mean())
print(arr_3.mean())

4.5
6.5
2.0
