In [1]:
# import the libraries

import numpy as np

In [2]:
arr_1 = np.array([1,2,3,4,5,6,7,8])
arr_1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
arr_1.ndim

1

In [4]:
arr_1.shape

(8,)

In [5]:
# Reshape (2,4)

a = arr_1.reshape(2,4)
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
# reshape (4,2)

b = arr_1.reshape(4,2)
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
# 1D array to  3D array 

In [8]:
c = arr_1.reshape(2,2,2)
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
c.ndim

3

In [10]:
b.ndim

2

In [11]:
a.ndim

2

In [12]:
# falatten 

c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
a = a.flatten()
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
b = b.flatten()
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
c = c.flatten()
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
# 3D array ()

d = np.array([
    [[6,5],[8,2]],
    [[1,2],[3,4]]
])

In [19]:
d

array([[[6, 5],
        [8, 2]],

       [[1, 2],
        [3, 4]]])

In [20]:
d = d.flatten()
d

array([6, 5, 8, 2, 1, 2, 3, 4])

In [21]:
# special reshape method 

arr_1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
arr_1.ndim

1

In [23]:
new_array = arr_1.reshape(1,-1)
new_array

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [24]:
new_array.ndim

2

In [25]:
new_array.shape

(1, 8)

In [26]:
arr_nw = arr_1.reshape(-1,1)
arr_nw

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [27]:
arr_nw.shape

(8, 1)