In [21]:
# impor library

import numpy as np

In [22]:
# create array 

a1 = np.array([
    [1,2,3],
    [4,5,6]
])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a2 = np.array([
    [10,12,14],
    [3,5,7]
])
a2

array([[10, 12, 14],
       [ 3,  5,  7]])

In [24]:
# Addition of array 

addition = a1 + a2
addition

array([[11, 14, 17],
       [ 7, 10, 13]])

In [25]:
# substraction 

sub = a1 - a2
sub

array([[ -9, -10, -11],
       [  1,   0,  -1]])

In [26]:
# multiplication 

mul = a1 * a2
mul

array([[10, 24, 42],
       [12, 25, 42]])

In [27]:
# division 

div = a1 / a2
div

array([[0.1       , 0.16666667, 0.21428571],
       [1.33333333, 1.        , 0.85714286]])