In [88]:
import numpy as np

In [89]:
# create matrics 

m1 = np.matrix("1,2,3;4,5,6")
m1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [90]:
m2 = np.matrix("7,8,9;12,15,13")
m2

matrix([[ 7,  8,  9],
        [12, 15, 13]])

In [91]:
#  matrix operation 
# addition 

add = m1 + m2
add

matrix([[ 8, 10, 12],
        [16, 20, 19]])

In [92]:
# substraction 

sub = m1 - m2
sub

matrix([[ -6,  -6,  -6],
        [ -8, -10,  -7]])

In [93]:
# division 

div = m1 / m2
div

matrix([[0.14285714, 0.25      , 0.33333333],
        [0.33333333, 0.33333333, 0.46153846]])

In [94]:
# transpose the matrix 

print(m2,"\n")

# method 1

m_2 = np.transpose(m2)
print(m_2)

[[ 7  8  9]
 [12 15 13]] 

[[ 7 12]
 [ 8 15]
 [ 9 13]]


In [95]:
# method 2

m2 = m2.T
print(m2)

[[ 7 12]
 [ 8 15]
 [ 9 13]]


In [96]:
# multiplication 

mul = m1 * m2
mul

matrix([[ 50,  81],
        [122, 201]])

# Stack 

In [97]:
m2 = m2.T

v = np.vstack((m1,m2))
print(type(v))
v

<class 'numpy.matrix'>


matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [12, 15, 13]])

In [98]:
h = np.hstack((m1,m2))
h

matrix([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 12, 15, 13]])

In [99]:
# example 

a_1 = np.zeros((5,),dtype = np.int16)

a_2 = np.ones((5,),dtype = np.int16)

print(a_1)
print(a_2)

[0 0 0 0 0]
[1 1 1 1 1]


In [100]:
h1 = np.hstack((a_1,a_2))
print(type(h1))
h1

<class 'numpy.ndarray'>


array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int16)

In [101]:
h1 = h1.reshape(-1,1)
h1

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int16)